#font_family      JetBrainsMono Nerd Font
font_family      Roboto Mono SemiBold
bold_font        Roboto Mono Bold
italic_font      Roboto Mono Medium Italic
font_size        14.0

include ./theme.conf
