#font_family      JetBrainsMono Nerd Font
font_family      JetBrains Mono SemiBold
bold_font        JetBrains Mono Bold
italic_font      JetBrains Mono Medium Italic
font_size        14.0

include ./theme.conf
